export const messageConstants = {
    LOGIN_SUCCESS: 'Login successful',
    LOGIN_FAILED: 'Login failed',
    LOGOUT_SUCCESS: 'Logged out successful',
    LOGOUT_FAIL: 'Log out was NOT successful',
    REGISTRATION_SUCCESS: 'Registration successful',
    REGISTRATION_FAILED: 'Registration failed',
    CATCH_MESSAGE: 'Unable to process this request',
    FOUND: 'Service responded successfully',
    CREATED: 'Resource created successfully',
    UPDATED: 'Resource updated successfully',
    NOT_UPDATED: 'Resource was not updated',
    FAILED: 'Resource creation failed',
    NOT_FOUND: 'Resource not found',
    DELETED: 'Resource removed successfully',
    INVALID_PARAMS: 'Invalid parameter passed to service',
    INVALID_EMAIL: 'Invalid email. Please provide a valid email',
    UNAUTHORIZED_EMAIL: 'Not authorized. Unknown account email or password',
    EMAIL_EXIST: 'An account with provided email already exist',
    ERROR_500: 'Unable to process this request',
    NOT_AUTHORIZED: 'Protected resource. Authentication/Authorization required.',
    MISSING_FIELDS: 'Missing required field(s)',
    MISSING_URL_ID: 'Missing required url parameter',
    PASSWORD_RESET_SUCESS: 'Password reset request was successful',
    PASSWORD_RESET_FAILED: 'Unable to reset password',
    PROJECT_NAME_EXIST: 'Project name already exist',
    PROJECT_TAG_EXIST: 'Project tag already exist',
    PROJECT_ORDER_CREATED: 'Project order was created successfully',
    PROJECT_ORDER_FAILED: 'Unable to create project order',
    PROJECT_CREATION_FAILED: 'Project order was created successfully',
    ORDER_CREATION_FAILED: 'Unable to create project order',
    GENERIC: 'Task successful',
    VALIDATION_FAILED: 'Validation failed',
};

export const requestConstants = {
    BODY: 'body',
    PARAMS: 'params',
    QUERY: 'query',
};

export const tokenConstants = {
    HASH_ROUND: 10,
    BASE_CONSTANT: 999999,
    TOKEN_ALGO: 'RS256',
    TOKEN_TIME: '24h',
    TOKEN_ISSUER: 'TOKEN_ISSUER',
};
